[package]
name = "async-graphql-poem"
version = "0.1.0"
edition = "2018"

[dependencies]
async-graphql = { path = "../..", version = "2.9.11" }

poem = "0.3.3"
serde_json = "1.0.66"
futures-util = { version = "0.3.13", default-features = false }
